{{- range .Values.users }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: "{{ $.Chart.Name }}-{{ . }}"
  name: "{{ $.Chart.Name }}-{{ . }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ $.Chart.Name }}-{{ . }}"
  template:
    metadata:
      labels:
        app: "{{ $.Chart.Name }}-{{ . }}"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - none
      initContainers:
      - name: volume-mount-set-www-data-permissions
        image: busybox
        command: ["sh", "-c", "chmod -R 777 /tmp/docker"]
        volumeMounts:
        - name: {{ . }}-home
          mountPath: /tmp/docker
      containers:
      - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        name: "{{ $.Chart.Name }}-{{ . }}"
        env:
        - name: SQLITE_DATABASE
          value: mydb
        - name: NEXTCLOUD_ADMIN_USER
          value: {{ . }}
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: {{ $.Values.password }}
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: nextcloud.k8s-prod.pharmb.io
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "100m"
            memory: 200Mi
        volumeMounts:
        - mountPath: /var/www/html/data/
          name: {{ . }}-home
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
#      securityContext:
#        # allow www-data to write volume
#        sGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      {{ if $.Values.existingClaim }}
      - persistentVolumeClaim:
          claimName: {{ $.Values.existingClaim }}
        name: {{ . }}-home
      {{else}}
      - hostPath:
          path: /media/scratch/{{ . }}-home/
          type: DirectoryOrCreate
        name: {{ . }}-home
      {{end}}
{{- end }}
