{{- if .Values.ingress.enabled -}}
{{- range .Values.users }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels:
    app: "{{ $.Release.Name }}-{{ . }}"
  name: "{{ $.Release.Name }}-{{ . }}"
  namespace: labinf
spec:
  rules:
  - host: pharmbio-notebook.{{ . }}.{{ $.Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: "{{ $.Release.Name }}-{{ . }}"
          servicePort: 80
        path: /
  tls:
  - hosts:
    - pharmbio-notebook.{{ $.Release.Name }}-{{ . }}.{{ $.Values.ingress.host }}
    secretName: "notebook-tls-{{ $.Release.Name }}-{{ . }}"

{{- end }}
{{- end }}

