{{- range .Values.users }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: "{{ $.Release.Name }}-{{ . }}"
  name: "{{ $.Release.Name }}-{{ . }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ $.Release.Name }}-{{ . }}"
  template:
    metadata:
      labels:
        app: "{{ $.Release.Name }}-{{ . }}"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - none
      containers:
      - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        name: "{{ $.Release.Name }}-{{ . }}"
        env:
        - name: PASSWORD
          value: '{{ $.Values.rstudioPass }}'
        ports:
          - containerPort: 8787
        resources:
          {{- toYaml $.Values.resources | nindent 12 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}
