{{- if .Values.ingress.enabled -}}
{{- range .Values.users }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 2000m
    kubernetes.io/tls-acme: "true"
  labels:
    app: "{{ $.Chart.Name }}-{{ . }}"
  name: "{{ $.Chart.Name }}-{{ . }}"
  namespace: labinf
spec:
  rules:
  - host: nextcloud.{{ . }}.{{ $.Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: "{{ $.Chart.Name }}-{{ . }}"
          servicePort: 80
        path: /
  tls:
  - hosts:
    - nextcloud.{{ . }}.{{ $.Values.ingress.host }}
    secretName: "nextcloud-tls-{{ $.Chart.Name }}-{{ . }}"

{{- end }}
{{- end }}

