{{- range .Values.users }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Chart.Name }}-{{ . }}"
  labels:
    app: "{{ $.Chart.Name }}-{{ . }}"
  namespace: labinf
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: "{{ $.Chart.Name }}-{{ . }}"
  sessionAffinity: None
  type: ClusterIP
{{- end }}
