{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-issuer"
  labels:
    app: "{{ .Release.Name }}"
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Release.Name }}.{{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: "{{ .Release.Name }}"
            port:
              number: 80

  tls:
  - hosts:
    - {{ .Release.Name }}.{{ .Values.ingress.host }}
    secretName: "notebook-tls-{{ .Release.Name }}"

{{- end }}

