---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: {{ $.Values.container_port }}
{{- if .Values.ssh.enabled }}
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
{{- end }}
  selector:
    app: "{{ .Release.Name }}"
  sessionAffinity: None
  type: ClusterIP
