{{- range .Values.users }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
#    nginx.ingress.kubernetes.io/auth-realm: Zeppelin - Authentication Required
#    nginx.ingress.kubernetes.io/auth-secret: zeppelin-auth-secret
#    nginx.ingress.kubernetes.io/auth-type: basic
  labels:
    app: "ml-container-{{ . }}"
  name: "ml-container-{{ . }}"
  namespace: labinf
spec:
  rules:
  - host: notebook.{{ . }}.k8s-prod.pharmb.io
    http:
      paths:
      - backend:
          serviceName: "ml-container-{{ . }}"
          servicePort: 80
        path: /
  tls:
  - hosts:
    - notebook.{{ . }}.k8s-prod.pharmb.io
    secretName: notebook-tls-ml-container-{{ . }}

{{- end }}


