{{- range .Values.users }}
---
apiVersion: v1
kind: Service
metadata:
  name: "ml-container-{{ . }}"
  labels:
    app: "ml-container-{{ . }}"
  namespace: labinf
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: "ml-container-{{ . }}"
  sessionAffinity: None
  type: ClusterIP
{{- end }}
