{{- range .Values.users }}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app: "{{ $.Release.Name }}-{{ . }}"
  name: "{{ $.Release.Name }}-{{ . }}"
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ $.Release.Name }}-{{ . }}"
  template:
    metadata:
      labels:
        app: "{{ $.Release.Name }}-{{ . }}"
    spec:
      {{- if or $.Values.gpuAccess.enabled $.Values.tfSupport.enabled}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - gpu
      {{- end }}
      {{- if $.Values.nodeSelector}}
      nodeSelector:
        {{toYaml $.Values.nodeSelector}}
      {{- end}}
      initContainers:
      - name: volume-mount-set-permissions-on-nfs-volume-home-mount
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /home/jovyan"]
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-home
          subPath: {{ . }}-home
      containers:
      - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        name: "{{ $.Release.Name }}-{{ . }}"
        command:
          - "/entrypoint.sh"
        env:
          - name: NOTEBOOK_PASSW_SHA1
            value: '{{ $.Values.notebookPasswSha1 }}'
        ports:
          - containerPort: 8888
        resources:
          limits:
          {{- toYaml $.Values.resources.limits | nindent 14 }}
            {{- if $.Values.gpuAccess.enabled -}}
            nvidia.com/gpu: "{{- $.Values.gpuAccess.gpus}}"
            {{- end }}
          requests:
          {{- toYaml $.Values.resources.requests | nindent 14 }}
            {{- if $.Values.gpuAccess.enabled -}}
            nvidia.com/gpu: "{{- $.Values.gpuAccess.gpus}}"
            {{- end }}
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-home
          subPath: {{ . }}-home
        - mountPath: /scratch-shared
          name: scratch-shared
        {{- range $.Values.secrets.secretNames }}
        - mountPath: {{ $.Values.secrets.secretsPath }}/{{ . }}
          name: {{ . }}-secret
        {{- end }}
        {{- range $.Values.extraVolumeClaims }}
        - mountPath: /mnt/{{ . }}
          name: {{ . }}
        {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        allowPrivilegeEscalation: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: notebook-home
        persistentVolumeClaim:
          claimName: notebook-homes-pvc
      - name: scratch-shared
        hostPath:
          path: /media/scratch/shared
          type: DirectoryOrCreate
      {{- range $.Values.secrets.secretNames }}
      - name: {{ . }}-secret
        secret:
          secretName: {{ . }}
      {{- end }}
      {{- range $.Values.extraVolumeClaims }}
      - name: {{ . }}
        persistentVolumeClaim:
          claimName: {{ . }}
      {{- end }}
{{- end }}
