---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ $.Release.Name }}"
    notebook-user: {{ required "User name of notebook is required, specifify in values.yaml or with --set" .Values.user }}
  name: "{{ $.Release.Name }}"
  namespace: "{{ $.Release.Namespace }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: "{{ $.Release.Name }}"
  template:
    metadata:
      labels:
        app: "{{ $.Release.Name }}"
    spec:
      {{- if $.Values.gpuAccess.enabled}}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - gpu
      {{- end }}
      {{- if $.Values.nodeSelector}}
      nodeSelector:
        {{toYaml $.Values.nodeSelector}}
      {{- end}}
      initContainers:
      - name: volume-mount-set-permissions-on-nfs-volume-home-mount
        image: gcr.io/google-containers/busybox
        command: ["sh", "-c", "chown 1000:1000 /home/jovyan"]
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-home
          subPath: {{ .Values.user }}-home
      containers:
      - image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        name: "{{ $.Release.Name }}"
        command:
          - "{{ $.Values.command }}"
        env:
          - name: NOTEBOOK_PASSW_SHA1
            value: '{{ $.Values.notebookPasswSha1 }}'
        ports:
          - containerPort: 8888
        securityContext:
          allowPrivilegeEscalation: true
        resources:
          limits:
            {{- toYaml $.Values.resources.limits | nindent 12 }} 
            {{- if $.Values.gpuAccess.enabled }}
            nvidia.com/gpu: "{{- $.Values.gpuAccess.gpus}}"
            {{- end }}
          requests:
            {{- toYaml $.Values.resources.requests | nindent 12 }}
            {{- if $.Values.gpuAccess.enabled }}
            nvidia.com/gpu: "{{- $.Values.gpuAccess.gpus}}"
            {{- end }}
        volumeMounts:
        - mountPath: /home/jovyan
          name: notebook-home
          subPath: {{ .Values.user }}-home
        - mountPath: /scratch-shared
          name: scratch-shared
        - mountPath: /dev/shm
          name: dshm
        {{- range $.Values.secrets.secretNames }}
        - mountPath: {{ $.Values.secrets.secretsPath }}/{{ . }}
          name: {{ . }}-secret
        {{- end }}

        {{- range $.Values.extraVolumeMounts }}                                                                
        - mountPath: {{ .mountPath }}                                                                          
          name: {{ .volumeName }}                                                                              
        {{- end }}
        {{- range $.Values.extraVolumeClaims }} # Deprecated, use extraVolumeMounts instead                    
        - mountPath: /mnt/{{ . }}                                                                              
          name: {{ . }}                                                                                        
        {{- end }}                
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
      - name: notebook-home
        persistentVolumeClaim:
          claimName: {{ $.Values.notebook_home_pvc_name }}
      - name: scratch-shared
        hostPath:
          path: {{ $.Values.scratch_disk_hostpath }}
          type: DirectoryOrCreate
      - name: dshm
        emptyDir:
          medium: Memory
      {{- range $.Values.secrets.secretNames }}
      - name: {{ . }}-secret
        secret:
          secretName: {{ . }}
      {{- end }}
      {{- range $.Values.extraVolumeMounts }}                                                                  
      - name: {{ .volumeName }}                                                                                
        persistentVolumeClaim:
          claimName: {{ .claimName }}                                                                          
      {{- end }}
      {{- range $.Values.extraVolumeClaims }} # Deprecated, use extraVolumeMounts instead                      
      - name: {{ . }}                                                                                          
        persistentVolumeClaim:                                                                                 
          claimName: {{ . }}                                                                                   
      {{- end }}
