---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: {{ $.Values.container_port }}
  selector:
    app: "{{ .Release.Name }}"
  sessionAffinity: None
  type: ClusterIP
