---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-{{ .Values.user }}"
  labels:
    app: "{{ .Release.Name }}-{{ .Values.user }}"
  namespace: "{{ .Release.Namespace }}"
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: "{{ .Release.Name }}-{{ .Values.user }}"
  sessionAffinity: None
  type: ClusterIP
