# Default values for ml-container.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

users:
  - student1
  - student2

rstudioPass: "sha1:126256b7627a:408ab6ac552a506d58872aae0ae4386892aa6606"

image:
  repository: pharmbio/rstudio-server-docker
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: "2"
    memory: 2000Mi
    nvidia.com/gpu: "0"
  requests:
    cpu: "1"
    memory: 1000Mi
    nvidia.com/gpu: "0"

ingress:
  enabled: true
  host: k8s-prod.pharmb.io

