---
{{- if and .Values.etcd.persistence.enabled (not .Values.etcd.persistence.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ if .Values.etcd.persistence.existingClaim }}{{ .Values.etcd.persistence.existingClaim }}{{ else }}{{ template "etcd.fullname" . }}-pvc{{ end }}
spec:
  accessModes:
    - {{ .Values.etcd.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.etcd.persistence.size | quote }}
{{- if .Values.etcd.persistence.storageClass }}
{{- if (eq "-" .Values.etcd.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.etcd.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
