---
apiVersion: v1
kind: Service
metadata:
  name: cheddar
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: cheese
    task: cheddar
