---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheese
spec:
  rules:
  - host: stilton.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: stilton
          servicePort: http
  - host: cheddar.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: http
  - host: wensleydale.{{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: wensleydale
          servicePort: http
