# Default values for ml-container.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# It is requred to specify a user name for notebook, this will be used for mounting
# /home/<user> on persistent storage
user: pharmbio-user

# Deprecated, use environmentVars below
notebookPasswSha1: null

# tag should be explicit version found at:
# https://cloud.docker.com/u/pharmbio/repository/docker/pharmbio/pharmbio-notebook
image:
  repository: pharmbio/pharmbio-notebook
  tag: tf-1.14.0-gpu
  pullPolicy: Always

container_port: 8888

command: "/entrypoint.sh"

#environmentVars:
#  - name: VAR1
#    value: value1
#  - name: VAR2
#    value: value2

resources:
  limits:
    cpu: "4"
    memory: 4000Mi
  requests:
    cpu: "1"
    memory: 1000Mi

# If enabled, will add gpu resource request/limit for provided number of gpus
gpuAccess:
  enabled: true
  gpus: 1

# default security
security:
  runAsNonRoot: true             # Default: run as root
  runAsUser: 1000                # If runAsNonRoot=true, use UID 1000
  allowPrivilegeEscalation: true # Default: same as now
  hostPathReadOnly: false        # Default: scratch hostPath is R/W
  dropCapabilities: []           # Default no dropping

# Each secret under secretNames will be mounted to the secretsPath folder in the container, see `kubectl get secrets` to list all visible secrets
#secrets:
#  secretsPath: /credentials
#  secretNames:
#    - mysql-chembl-credentials

ingress:
  enabled: true
  host: k8s-prod.pharmb.io

# PVC for notebook homes
container_user_home_pvc_name: notebook-homes-pvc

# directory in container that should be mounted to Persistent storage
container_user_home: /home/jovyan

# Hostpath scratch disk path
scratch_disk_hostpath: /media/scratch/shared

# List name of any pvc to be mounted, can be found under /home/shared/<pvc name> in notebook filesystem
# 
# Deprecated, use extraVolumeMounts
#extraVolumeClaims:
#  - micro-images-pvc

# List name of any pvc to be mounted, can be found under /home/shared/<pvc name> in notebook filesystem
#extraVolumeMounts:
#  - claimName: external-images-pvc
#    volumeName: external-images-pvc
#    mountPath: /share/external-images-pvc

# run notebook on speciffic node from labels, e.g. host: limpar
nodeSelector: {}

